Makefile
IVP-1168
running in docker so do not need start.sh and might not need the routes.yml
For drop 1 of this product this is all we need
=> Simplify makefile so I can release on Courcourse

README.md, src/main/java/uk/gov/companieshouse/ocr/api/heathcheck/HealthCheckController.java, src/test/java/uk/gov/companieshouse/ocr/api/heathcheck/HealthCheckControllerTest.java
Jira - IVP-1187
Add heath check controller (was planned for drop 2 but needed for ECS diagnostics)
=> add heathcheck

src/main/java/uk/gov/companieshouse/ocr/api/heathcheck/HealthCheckController.java
To help debug calling service on ECS
=> add logging when heath check is called

README.md, src/main/java/uk/gov/companieshouse/ocr/api/heathcheck/HealthCheckController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiController.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/ocr/api/IntegrationTest.java, src/test/java/uk/gov/companieshouse/ocr/api/heathcheck/HealthCheckControllerTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiControllerTest.java
Also and correct spelling mistake
This is required for how we will deploy the app in ECS
=> add context root for app 

README.md, src/main/java/uk/gov/companieshouse/ocr/api/common/ErrorResponseDTO.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ExtractTextResultDTO.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrService.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrTransformer.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/TextConversionException.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/TextConversionResult.java, src/test/java/uk/gov/companieshouse/ocr/api/IntegrationTest.java, src/test/java/uk/gov/companieshouse/ocr/api/heathcheck/HealthCheckControllerTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiControllerTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/TextConversionResultTest.java
Jira: ivp1282 
Add optional context id for when mulitple apps use this api
=> optional context id request parameter

src/main/java/uk/gov/companieshouse/ocr/api/logging/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/ocr/api/logging/LoggingInterceptor.java
Code changes to add a logging interceptor for ocr api service
Files modified:
new file:   src/main/java/uk/gov/companieshouse/ocr/api/logging/InterceptorConfig.java
new file:   src/main/java/uk/gov/companieshouse/ocr/api/logging/LoggingInterceptor.java
* [] Bug fix
=> Logging interceptor for ocr api service

Makefile
Need to get Sonar to run unit tests (and show code coverage)
=> use correct included-tests value

README.md, src/main/java/uk/gov/companieshouse/ocr/api/ThreadConfig.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrService.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrClientRequest.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequest.java, src/main/java/uk/gov/companieshouse/ocr/api/statistics/StatisticsService.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiControllerTest.java, src/test/java/uk/gov/companieshouse/ocr/api/statistics/StatisticsServiceTest.java
IVP-1511 (and see end to end reference in parent Jira)
This is part of allowing clients to send an asynchronous request to the ocr-api with callbacks for asynchronous processing (details in Jira)
=> add asynchonous end point and new thread pool in the configuration

src/main/java/uk/gov/companieshouse/ocr/api/SpringConfiguration.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrService.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageRestClient.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequest.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestException.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestService.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/ocr/api/TestObjectMother.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiControllerTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageRestClientTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestServiceTest.java
=> get image back from requesting system

Makefile, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrService.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestService.java, src/test/java/uk/gov/companieshouse/ocr/api/TestObjectMother.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiControllerTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestServiceTest.java
IVP-1513 Convert image (obtained from remote system) to text
Part of adding an async API to the ocr-api microservice
=> ivp convert image to text

src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/CallbackExtractedTextRestClient.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestException.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestService.java, src/test/java/uk/gov/companieshouse/ocr/api/TestObjectMother.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/CallbackExtractedTextRestClientTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageRestClientTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestServiceTest.java
Jira: ivp 1413 
Send results back to CHIPS (part of new ocr-api async functionality)
=> send ocr results back to chips

pom.xml, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrClientRequest.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestService.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageOcrApiControllerTest.java
=> Vet request for a body and mandatory parameters

src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/CallbackExtractedTextRestClient.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ExtractTextResultDto.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestException.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestService.java, src/test/java/uk/gov/companieshouse/ocr/api/TestObjectMother.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/CallbackExtractedTextRestClientTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/ExtractTextResultDtoTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestServiceTest.java
IVP-1519
Sending back errors in the Results sets to calling system (CHIPS at the moment)
=> adding sending back errors to calling system in results set

README.md, src/main/java/uk/gov/companieshouse/ocr/api/SpringConfiguration.java, src/main/java/uk/gov/companieshouse/ocr/api/ThreadConfig.java, src/main/java/uk/gov/companieshouse/ocr/api/common/JsonConstants.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/AbstractOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/AsyncImageOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/CallbackExtractedTextRestClient.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/ImageRestClient.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestException.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestService.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/SyncImageOcrApiController.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/AsyncImageOcrApiControllerTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/CallbackExtractedTextRestClientTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrRequestServiceTest.java, src/test/java/uk/gov/companieshouse/ocr/api/image/extracttext/SyncImageOcrApiControllerTest.java
ivp 1506 - limit queue size
IVP-1559 - Log client event
=> limit queue size to prevent ocr-api overloading

README.md
Add more information on logging to README
=> Add more information on logging to README

README.md
Need this to trigger a build with updated pipeline to see if a Latest tag is created
=> minor README change

README.md
=> add URL for testing with CHS docker (README change only)

README.md
Small punctuation change in read me
=> Puncuation in readme

pom.xml
JIRA ticket
[BI-13680](https://companieshouse.atlassian.net/browse/BI-13680)
Short description
Bump dependency version and added servlet dependency
[BI-13680]: https://companieshouse.atlassian.net/browse/BI-13680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump dependency version and added servlet dependency

pom.xml
Due to tomcat dependency version 11.0.0-M20 there was an error while deploying changes. The version 9.0.89 has fixed the isssue.https://mvnrepository.com/artifact/org.apache.tomcat.embed/tomcat-embed-core.
=> Fix for tomcat issue

src/main/java/uk/gov/companieshouse/ocr/api/healthcheck/HealthCheckController.java
An empty commit to trigger OCR pipeline to generate artefacts
=> An empty commit to trigger pipeline

ecs-image-build/Dockerfile, ecs-image-build/docker_start.sh, terraform/groups/ecs-service/data.tf, terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars, terraform/groups/ecs-service/variables.tf, terraform/groups/ecs-service/vault-providers/approle, terraform/groups/ecs-service/vault-providers/token, terraform/groups/ecs-service/vault-providers/userpass, terraform/groups/ecs-service/vault.tf, terraform/groups/ecs-service/version
Jira Ticket
Resolves: BI-13716
Short Description: Amend the ocr-api application to ecs-image-build and terraform folders
=> Amend the ocr-api application to include terraform

pom.xml, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/AsyncImageOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/OcrClientRequest.java, src/main/java/uk/gov/companieshouse/ocr/api/logging/LoggingInterceptor.java
Resolves: [BI-13718](https://companieshouse.atlassian.net/browse/BI-13718)
**Description**
Updated OCR-API from Java version 11 to 21
[BI-13718]: https://companieshouse.atlassian.net/browse/BI-13718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated OCR-API from Java 11 to 21

pom.xml, src/main/java/uk/gov/companieshouse/ocr/api/SpringConfiguration.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/AbstractOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/AsyncImageOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/image/extracttext/SyncImageOcrApiController.java, src/main/java/uk/gov/companieshouse/ocr/api/logging/LoggingInterceptor.java
Fix error in pom.xml, Upgraded tomcat dependency, removed unnecessary dependencies and organised imports
Resolves: ASM-366
=> Upgraded tomcat dependency, removed unnecessary dependencies and organised imports

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars, terraform/groups/ecs-service/variables.tf
Update service configs for all envs, including task memory
Updated var defaults
Alignment updates
=> Update service config

src/test/java/uk/gov/companieshouse/ocr/api/IntegrationTest.java
[ASM-401](https://companieshouse.atlassian.net/browse/ASM-401)
* fixed integration test (re-added an accidentally removed line)
[ASM-401]: https://companieshouse.atlassian.net/browse/ASM-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> asm 401 fix build failures in ocr-api
